server:
  port: 8089

spring:
  datasource:
    url: jdbc:h2:mem:microservico
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true

  flyway:
   schemas: PUBLIC